# Generated by Django 4.1.3 on 2022-11-28 11:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="наименование")),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subordinates",
                        to="organization.division",
                        verbose_name="головное подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "подразделение",
                "verbose_name_plural": "подразделения",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=60, verbose_name="фамилия")),
                ("first_name", models.CharField(max_length=60, verbose_name="имя")),
                (
                    "patronymic",
                    models.CharField(max_length=60, verbose_name="отчество"),
                ),
                ("age", models.SmallIntegerField(verbose_name="возраст")),
                ("position", models.CharField(max_length=60, verbose_name="должность")),
                (
                    "date_of_employment",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="дата приема на работу",
                    ),
                ),
                (
                    "wage",
                    models.IntegerField(default=0, verbose_name="заработная плата"),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="organization.division",
                        verbose_name="подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "сотрудник",
                "verbose_name_plural": "сотрудники",
            },
        ),
    ]
